name: Build Ghostwolf

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build the solution
        run: msbuild Ghostwolf.sln \
              /p:Configuration=Release \
              /p:Platform=x64 \
              /p:OutDir=${{ github.workspace }}\artifacts\

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ghostwolf-x64-Release
          path: artifacts/Ghostwolf.exe
          # 或者用通配符：
          # path: |
          #   **/Ghostwolf.exe
