name: Build Ghostwolf

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Command Prompt
        # 推荐使用 ilammy 的 Action
        uses: ilammy/msvc-dev-cmd@v1

      # 或者，如果你更倾向 TheMrMilchmann 的实现，可替换为：
      # uses: TheMrMilchmann/setup-msvc-dev@v3

      - name: Build the solution
        run: msbuild Ghostwolf.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ghostwolf-x64-Release
          path: Ghostwolf/x64/Release/Ghostwolf.exe
